# Generated by Django 3.0.7 on 2020-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_txt', models.TextField(default='-')),
                ('body_txt', models.TextField(default='-')),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(default='00:00', max_length=12)),
                ('imgname', models.TextField(default='-')),
                ('imgurl', models.TextField(default='-')),
                ('writer', models.CharField(max_length=50)),
                ('category', models.CharField(default='category', max_length=200)),
                ('catid', models.IntegerField(default=0)),
                ('ocatid', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
            ],
        ),
    ]
