# Generated by Django 3.0.7 on 2020-08-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rand',
            field=models.IntegerField(default=0),
        ),
    ]
