# Generated by Django 3.0.7 on 2020-06-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200622_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='add',
            field=models.TextField(default='Address here'),
        ),
        migrations.AddField(
            model_name='main',
            name='eml',
            field=models.TextField(default='Your Email here'),
        ),
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.TextField(default='any link here'),
        ),
        migrations.AddField(
            model_name='main',
            name='tell',
            field=models.TextField(default='contact number'),
        ),
    ]
