# Generated by Django 3.0.7 on 2020-06-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200622_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='add',
            field=models.CharField(default='Address here', max_length=500),
        ),
        migrations.AlterField(
            model_name='main',
            name='eml',
            field=models.CharField(default='Your Email here', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(default='FaceBook', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(default='any link here', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='lkdn',
            field=models.CharField(default='LinkdIn', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='setting', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='tell',
            field=models.CharField(default='contact number', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='Twitter', max_length=30),
        ),
    ]
