# Generated by Django 3.0.7 on 2020-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200622_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='imgname',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='main',
            name='imgurl',
            field=models.TextField(default=' '),
        ),
    ]
