# Generated by Django 3.0.7 on 2020-07-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cate',
            new_name='Cat',
        ),
    ]
